### ISSUE TITLE
Holland version update

### ISSUE THREAD

**Issue by rax-rstark** [rcbops/openstack-ops#160]
https://github.com/rcbops/openstack-ops/blob/e071f104800f249cc1ce6619847258041070b6e1/playbooks/vars/holland.yml#L25

Any reason we do not install `holland 1.1.20` (last version with python2 support) for branch `ansible-eol`, and `holland 1.2.1` for `master` branch?

reference: https://github.com/holland-backup/holland/releases

**Comment by BjoernT** [comment]
OK I updated the version
