### ISSUE TITLE
iLO version update for HPE DL380 Gen9 platform

### ISSUE THREAD

**Issue by rax-rstark** [rcbops/openstack-ops#184]
HPE updated it's iLO version from 2.78 to 2.79 on 2021-11-25. (Who releases updates on Thanksgiving?):

https://support.hpe.com/hpesc/public/swd/detail?swItemId=MTX_97f5079671c84a11ac776a92cb

Please update master & ansible-eol branches to use new iLO version, as HPE support is requesting we update to that version prior to them resolving any outstanding HW issues.

**Comment by BjoernT** [comment]
OK added
