### ISSUE TITLE
HPE DL380 Gen9  iLO  update  (2.80)

### ISSUE THREAD

**Issue by rax-rstark** [rcbops/openstack-ops#195]
HPE has updated it's iLO version in April to version 2.80: 

(HPE login restricted page)
https://support.hpe.com/connect/s/softwaredetails?language=en_US&softwareId=MTX_7ce18ea0b6834e5b810bbfd728

Version: 2.80
Release Date: Apr 8, 2022

```
md5sum firmware-ilo4-2.80-1.1.i386.rpm
fbacb509bb0f50eac6e8b792f652c01f  firmware-ilo4-2.80-1.1.i386.rpm
```

I'll note that this particular update is listed as 'critical, must update' by the vendor, as it addresses a rootkit vulnerability detailed here:

https://support.hpe.com/hpesc/public/docDisplay?docId=emr_na-a00120318en_us

Request to update `update_hp_firmware.py` in `main` & `ansible-eol` branches to accommodate.

**Comment by BjoernT** [comment]
Updated per https://github.com/rcbops/openstack-ops/commit/29e64a24594ea6d95af8ad6ae1109f0b923468c6 and https://github.com/rcbops/openstack-ops/commit/6e79f15371d3e26ead2e5cedb7fb15b882663070
