### ISSUE TITLE
HPE DL380 Gen9 iLO Update (2.81)

### ISSUE THREAD

**Issue by rax-rstark** [rcbops/openstack-ops#205]
HPE updated it's iLO version from 2.80 to 2.81 on 2022-09-07:

https://support.hpe.com/connect/s/softwaredetails?softwareId=MTX_47590c9ba0974132ba3946e21d

```
$ md5sum firmware-ilo4-2.81-1.1.i386.rpm
3de78fcb64f45e365de0d6bc8dd54d14  firmware-ilo4-2.81-1.1.i386.rpm
```

Request to update update_hp_firmware.py script, both master & ansible-eol branches to accommodate.

**Comment by BjoernT** [comment]
I added the firmware update to the script
