### ISSUE TITLE
HPE DL380 Gen9 Smart HBA Update (7.20)

### ISSUE THREAD

**Issue by rax-rstark** [rcbops/openstack-ops#206]
HPE updated it's Smart HBA storage controller version from 7.00. to 7.20 on 2020-09-07:

https://support.hpe.com/connect/s/softwaredetails?softwareId=MTX_26880c85fb3e4f5897e03283cc

```
$ md5sum firmware-smartarray-ea3138d8e8-7.20-1.1.x86_64.rpm
8d8d0cf7fe0cfab9dc4963384da3041b  firmware-smartarray-ea3138d8e8-7.20-1.1.x86_64.rpm
```

Request to update update_hp_firmware.py script, both master & ansible-eol branches to accommodate.

**Comment by BjoernT** [comment]
I added the firmware update to the script
