### ISSUE TITLE
HPE DL380 Gen9 BIOS Update (3.30)

### ISSUE THREAD

**Issue by ryansyah** [rcbops/openstack-ops#211]
HPE updated it's BIOS version from 3.08 to 3.30 on 2023-10-05:

https://support.hpe.com/connect/s/softwaredetails?collectionId=MTX-ce0053f84e284a99&softwareId=MTX_0be8a0d8f06a491bbccc434186

```
$ shasum -a 256 firmware-system-p89-3.30_2023_09_21-1.1.i386.rpm
88170a7044f9f912ec48256ed665d3c6bb716158af77cbd64a750ee3e34557ab  firmware-system-p89-3.30_2023_09_21-1.1.i386.rpm
```

Please update update_hp_firmware.py script in master & ansible-eol branches to to accommodate.

**Comment by BjoernT** [comment]
Please attach the file as I dont have access to the HPE support site

**Comment by BjoernT** [comment]
Updated

`Verifying current SYSTEM version: Needs update (01/12/2023 -> 09/21/2023)
http://d490e1c1b2bxxxxxxx368e2db0220301cd1330e.r14.cf5.rackcdn.com/hp-firmware-system-p89-3.30_2023_09_21-1.1.i386.rpm
Downloading hp-firmware-system-p89-3.30_2023_09_21-1.1.i386.rpm  -> Success!
Checking MD5: Match!
Extracting firmware: Success!
Flashing...
Success!
Writing log to /root/hpfw-upgrade-2024-01-26-04-49-46/SYSTEM.log`

**Comment by rax-rstark** [comment]
ansible-eol missing fix
